# Generated by Django 3.2 on 2025-06-12 13:35

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "verbose_name": ("Жанр",),
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Название элемента",
                max_length=256,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Название элемента",
                max_length=256,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Краткое содержание произведения",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.SmallIntegerField(
                db_index=True,
                help_text="Используйте формат для года <YYYY>",
                validators=[reviews.validators.validate_year],
                verbose_name="Год",
            ),
        ),
    ]
